custom_users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('user_list', views.UserListView.as_view(), name='user_list')
]

main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persons.urls')),
    path('', include('custom_users.urls')),
    path('', include('parser_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

persons/urls.py
from django.urls import path
from . import views

app_name = 'persons'
urlpatterns = [
    path('person_list/', views.PersonListView.as_view(), name='person_list'),
    path('person_list/<int:id>/', views.PersonDetailView.as_view()),
    path('person_list/<int:id>/delete/', views.PhoneDeleteView.as_view()),
    path('person_list/<int:id>/update/', views.PersonUpdateView.as_view()),
    path('create_person/', views.PersonCreateView.as_view()),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<div style="background-color: lightpink">
  <h1>Вы увернны что хотите удалить?</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button style="width: 100px; height: 100px;" type="submit">Да</button>
  </form>
     <button style="width: 100px; height: 100px;">
         <a style="text-decoration: none; color: black" href="/person_list/">Нет</a>
     </button>
</div>
</body>
</html>

templates/film_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for i in object_list %}
    <li>
        <a href="{{i.title_url}}"><h1>{{i.title_name}}</h1></a>
        <img src="{{i.image}}" alt="">
    </li>
    {% endfor %}
</ul>
</body>
</html>

templates/manas_parser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parser</title>
</head>
<body>
<center>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Взять данные</button>
  </form>
  <a href="/film_list/">Фильмы</a>
</center>
</body>
</html>

templates/person_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person Create</title>
</head>
<body>
<div style="background-color: aquamarine">
  <h1>Создать</h1>
  <form action="/create_person/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Добавить</button>
    <button type="reset">Очистить</button>
  </form>
</div>
</body>
</html>

templates/person_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PersonDetail</title>
</head>
<body>
<div style="background-color: darksalmon">
  <h1>Имя:{{object.name}}</h1>
  <p>Возраст:{{object.age}}</p>
  <p>Хобби:{{object.hobby}}</p>
  <p>Пол:{{object.gender}}</p>
  <p>Номер:{{object.phone_number}}</p>
</div>
</body>
</html>

templates/person_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PersonList</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Навбар</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Ссылка</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Выпадающий список
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Действие</a></li>
                        <li><a class="dropdown-item" href="#">Другое действие</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Что-то еще здесь</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Отключенная</a>
                </li>
            </ul>
            <form action="{% url 'persons:search' %}" method="GET" class="d-flex" role="search">
                <input class="form-control me-2" name="q" type="search" type="text" placeholder="Поиск"
                       aria-label="Поиск">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>

            <form action="{% url 'users:login' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Выйти</button>
            </form>
        </div>
    </div>
</nav>
<div style="background-color: darksalmon">
    <center>
        <h1>CRUD</h1>
        <button style="width: 100px; height: 50px; background-color: lawngreen">
            <a href="/create_person/">Добавить</a>
        </button>
    </center>
</div>

<div class="block1" style="background-color: darkgray;">

    <ul>
        {% for i in object_list %}
        <li>
            <h1>Имя:{{i.name}}</h1>
            <p>Возраст:{{i.age}}</p>
            <a href="/person_list/{{i.id}}/" class="a1">Детально</a>
            <a href="/person_list/{{i.id}}/delete/" class="a2">Удалить</a>
            <a href="/person_list/{{i.id}}/update/" class="a3">Изменить</a>
        </li>
        {% endfor %}
    </ul>
</div>
<style>
    .block1 a {
        text-decoration: none;
        font-size: 30px;
    }

    .a1 {
        color: green;
        border: 4px solid green;
    }

    .a2 {
        color: red;
        border: 4px solid red;
    }

    .a3 {
        color: #65550c;
        border: 4px solid #65550c;
    }

</style>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

templates/person_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person_Update</title>
</head>
<body>
<div style="background-color: yellow">
  <h1>Изменить</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Изменить</button>
    <button type="reset">Очистить</button>
  </form>
</div>
</body>
</html>